batch/urls.py
from django.conf.urls import url
from . import views

#app_name = 'music'
urlpatterns = [

    #/batch/
    url(r'^$', views.index, name='index'),

    #/batch/id
    url(r'^(?P<batch_id>[0-9]+)/$', views.batch_students, name = 'batch_students'),

    url(r'^(?P<batch_id>[0-9]+)/update_data/$', views.update_data, name='update_data'),
]

varsito/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^batch/', include('batch.urls')),
]

batch/models.py
from django.db import models

# Create your models here.

class Batch(models.Model):
    batch_name = models.CharField(max_length=100)
    batch_stream = models.CharField(max_length=100)
    batch_class = models.CharField(max_length=100)
    batch_contact = models.CharField(max_length=100)

    def __str__(self):
        return self.batch_name+' - '+self.batch_stream


class Student(models.Model):
    batch = models.ForeignKey(Batch, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    student_contact = models.CharField(max_length=100)
    student_email = models.CharField(max_length=100, default='abc@example.com')
    student_DOB = models.CharField(max_length=100, default='dd/mm//yyyy')
    def __str__(self):
        return self.first_name+' '+self.last_name

batch/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Batch
# Create your views here.

def index(request):
    all_batches = Batch.objects.all()
    return render(request, 'batch/index.html', {'all_batches': all_batches})

def batch_students(request, batch_id):
    batch = get_object_or_404(Batch, pk = batch_id)
    return render(request, 'batch/batch_students.html', {'batch':batch})

def update_data(request, batch_id):
    batch = Batch.objects.get(pk = batch_id)
    return render(request, 'batch/update_data.html', {'batch':batch})

batch/templates/batch/batch_students.html
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<div class="container">
    <h3><span class="label label-info">Batch Name  </span><span class="label label-success">{{ batch.batch_name }} </span> </h3>
    <h4><span class="label label-info">Stream  </span><span class="label label-success">{{ batch.batch_stream }}</span> </h4>
    <h4><span class="label label-info">Contact No.  </span><span class="label label-success">{{ batch.batch_contact }}</span> </h4>
    <h2><b><span class="label label-warning">Student Details  </span></b></h2>

    <table style="width:100%">
        <tr>
            <div class="row">
                <th>First Name</th>
                <th>Last Name</th>
                <th>Contact No</th>
                <th>Email</th>
                <th>Date of Birth</th>
            </div>
        <style>
            table {
                color: #333;
                font-family: Helvetica, Arial, sans-serif;
                width: 640px;
                border-collapse:
                collapse; border-spacing: 0;
            }

            td, th{
                border: 1px solid transparent; /* No more visible border */
                height: 30px;
                transition: all 0.3s;  /* Simple transition for hover effect */
                text-align: center;
            }

            th {
                background: #DFDFDF;  /* Darken header a bit */
                font-weight: bold;
            }

            td {
                background: #FAFAFA;
                text-align: center;
            }

            /* Cells in even rows (2,4,6...) are one color */
            tr:nth-child(even) td { background: #F1F1F1; }

            /* Cells in odd rows (1,3,5...) are another (excludes header cells)  */
            tr:nth-child(odd) td { background: #FEFEFE; }

            tr:hover { background: black; color: red; }*/
            /* Hover cell effect! */
        </style>

      </tr>
        {% for student in batch.student_set.all %}
            <tr>
                <td>{{ student.first_name }}</td>
                <td>{{ student.last_name }}</td>
                <td>{{ student.student_contact }}</td>
                <td>{{ student.student_email }}</td>
                <td>{{ student.student_DOB }}</td>

            </tr>
        {% endfor %}
    </table>
    <a href="/batch/{{ batch.id }}/update_data/" class="btn btn-primary">Update</a>
</div>

batch/templates/batch/index.html
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<h3><span class="label label-info">List of all Batches </span></h3>
{% if all_batches %}
    <ul>
        {% for batch in all_batches %}
            <li><a href = "/batch/{{ batch.id }}"><h3><span class="label label-primary" >{{ batch.batch_name }}</span></h3></a></li>
        {% endfor %}
    </ul>
{% else %}
    <h3>You don't have any batch</h3>
{% endif %}

batch/templates/batch/update_data.html
<!DOCTYPE html>
<html>
<body>

<form action="/batch/{{ batch.id }}/">

  {% for student in batch.student_set.all %}
      Contact No:<br>
      <input type="text" name="Contact No." value="{{ student.student_contact }}">
      <br>
      Email <br>
      <input type="text" name="Email" value="{{ student.student_email }}">
  <br><br>
  {% endfor %}
  <input type="submit" value="Update">
</form>

</body>
</html>